name: rank
version: '${project.version}'
main: me.cole.rankplugin.Rank
api-version: '1.20'
commands:
  rank:
    usage: /rank <user> <set|display> [group]
    description: Update or display a users group

